
name: Docker Image CI



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag buckstore.auth:latest
        docker login -u ${DOCKERHUBUSER} -p ${DOCKERHUBPASS}
        docker push buckstore.auth:latest
      env: 
        DOCKERHUBUSER: ${{secrets.DOCKER_HUB_USER_NAME}}
        DOCKERHUBPASS: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
