name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag buckstore.auth:$(date +%s)
        git tag latest
        git push origin --tags
        docker push buckstore.auth:$(date +%s)
      env: 
        DOCKERHUBUSER: ${{secrets.DOCKERHUBUSER}}
        DOCKERHUBPASS: ${{secrets.DOCKERHUBPASS}}
